test/helper.py

First in a series of PRs to backport changes from  [wisp3rwind/beets-alternatives](https://github.com/wisp3rwind/beets-alternatives) to this repo
Very minor fix to test setup that didn't even lead to test failures:
```
The color config option has been moved to ui.color
and while beets used to respect the legacy top-level color config
(emitting a deprection warning, though), it doesn't since the following commit:
be8fe875 commit 2016-09-25 - Remove deprecated top level colors config option (#2209)
```

[1/?] The color config option has been moved to ui.color

---

beetsplug/alternatives.py
test/helper.py

Second in a series of PRs to backport changes from  [wisp3rwind/beets-alternatives](https://github.com/wisp3rwind/beets-alternatives) to this repo
```
Use the logger provided as BeetsPlugin._log, fixes parallel imports crashing...
...on a log level assertion in recent beets versions. Originally, this
fix was committed in 2016, and I don't quite remember the circumstances
crashes happened under. However, looking at the code for beets.plugins,
beets is clearly expecting plugins to use the logger provided through
the plugin class. Thus, it seems this change should be applied whether
or not these crashes could still occur.
```

[2/?] Use the logger provided as BeetsPlugin._log, fixes parallel imports crashing

---

.travis.yml
CHANGELOG.md
beetsplug/alternatives.py
setup.py
test/cli_test.py
test/helper.py
tox.ini

As the title says. In particular all paths are now treated with beets' `bytestring_path`/`syspath`/`displayable_path` machinery. I hope I got it all right, this is quite large and I'm not an expert on unicode handling in beets. Types for path storage in the database should not be an issue since Python's `sqlite3` library will by default return `TEXT` columns (as are all flexible attributes) as Unicode objects across all Python versions. Nevertheless, I'd appreciate if someone (...) could upgrade beets from Python 2 to 3 and ensure that not all of the files get added to the alternative collection again (after having taken a backup, of course).
Travis and tox configs are adapted accordingly. 
Closes #18

Support Python 3

---

CHANGELOG.md
beetsplug/alternatives.py

Allows some (two to be precise) aliases to be used in the formats config option, cf. [convert.py](https://github.com/beetbox/beets/blob/b380a4c9a37640f93b02c3277af5e76d4e8567e9/beetsplug/convert.py#L41):
```python
ALIASES = {
u'wma': u'windows media',
u'vorbis': u'ogg',
}
```

Support format aliases from the convert plugin

---

CHANGELOG.md
beetsplug/alternatives.py
test/cli_test.py

This matches the behaviour of the convert plugin, see [its source](https://github.com/beetbox/beets/blob/b380a4c9a37640f93b02c3277af5e76d4e8567e9/beetsplug/convert.py#L319). Without this `write` call, tags in the new file can easily be be incomplete/missing: Even if the encoding program does write tags, it might not map them between formats in the way that beets would.
This was the reason behind some recent "corruption" of my alternative collection: Newly added files didn't contain any tags, not even title or artist. I did not try to check what triggered this (I hadn't changed any of beets' configuration), but I would suspect that some new release of ffmpeg changed its behaviour to not write tags anymore.
I guess it would be nice to have a test, but I'm not sure how to set it up. In some …

Explicitly write tags after initial conversion

---

CHANGELOG.md
beetsplug/alternatives.py
test/cli_test.py
test/helper.py

Consider the following scenario:
Initial configuration:
```yaml
alternatives:
myexternal:
formats: m4a wma
```
add a file:
```
+/path/to/track 1.wma
```
At some point (maybe due to a new media player not supporting wma), you change this to
```yaml
alternatives:
myexternal:
formats: m4a
```
On the next update, this will happen:
```
>/path/to/track 1.wma -> /path/to/track 1.m4a
```
While it's not feasible to detect every kind of format change (which might be minor such as modified target bitrates), `beets-alternatives` should not rename files to incorrect extensions, but actually reencode in these cases. Hence this PR.
~~(The PR is relative to #26)~~

Don't corrupt files on format change

---

.travis.yml
tox.ini

now that beets supports them.
Actually, it might be nice to setup a [Travis cron job](https://docs.travis-ci.com/user/cron-jobs/) to regularly (say, weekly) run tests against recent beets. Does that sound good to you @geigerzaehler?

Add Python 3.7 and 3.8 to travis build matrix and tox config

---

.travis.yml

As discussed in #28. I added my (encrypted, https://docs.travis-ci.com/user/encryption-keys) mail for notifications, the PR is mostly to check whether I got the travis syntax right.

Enable travis email notifications

---

README.md

As the title says, I just noticed that the coveralls badge used the PNG image, which does not look very pretty next to the SVG Travis badge. Coveralls.io also thinks that there's no badge at all:
> We detected this repo isn’t badged! Grab the embed code to the right, add it to your repo to show off your code coverage, and when the badge is live hit the refresh button to remove this message.

update coveralls badge to use svg and new URL

---

test/cli_test.py
test/helper.py

The tests that I added are fairly simple though, but hopefully still better than nothing. Now waiting for Travis...

Improve test coverage

---

README.md
beetsplug/alternatives.py
test/cli_test.py
test/helper.py

Related to #34 
I would simply replace absolute path symlinks with relative path ones, but I understand that a config option would be necessary to let the user select which kind of links to use

Use relative symlinks

---

beetsplug/alternatives.py

I also added the parser name as 'beet alt', by default it was `sys.argv[0]` which was only `beet`, causing help to show usage as `usage: beet update [-h] [--create] [--no-create] name` instead of `beet alt update`.

Fixing cli bug #35

---

CHANGELOG.md
beetsplug/alternatives.py
test/cli_test.py

Add the `_get_all_options()` method to the argument parser so that `beet completion` does not throw an error anymore.
Fixes https://github.com/geigerzaehler/beets-alternatives/issues/38

Avoid crashing 'beet completion'

---

.travis.yml
setup.cfg
setup.py
tox.ini

- Bump python versions
- travis appears to use Xenial everywhere nowadays, so no need to force this distribution in order to get recent Python
- the `sudo` keyword was deprecated because travis now uses a fully virtualized infrastructure: [link](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration#timeline---its-happening-fast)

Update travis configuration

---

CHANGELOG.md
README.md
beetsplug/alternatives.py
test/cli_test.py

Closes #45
Add a list-tracks command that prints all tracks that are part of a collection.
@sindreruud could you have a look at this and check if this would work for you?

Add list-tracks command

---

beetsplug/alternatives.py

See https://github.com/geigerzaehler/beets-alternatives/pull/48#issuecomment-602186433 : So long as Python 2 is not entirely burried, we might want to specify the source encoding explicitly. Related: [PEP 263](https://www.python.org/dev/peps/pep-0263/).

specify encoding to fix importing the plugin on Python 2

---

.travis.yml

Beets 1.4.9 is not compatible with Python 3.9. We remove it from the CI build matrix.

Remove beets 1.4.9 and Python 3.9 from CI

---

CHANGELOG.md
beetsplug/alternatives.py
test/cli_test.py

The first commit implements a test for the scenario from #47. The others fix it:
- beets' `util.remove(path, soft=True)` is always a no-op for symlinks...
- separate the logic for detecting changes for `External`/`ExternalConvert` collections and `SymlinkView`s since they have somewhat different semantics.
**Todo:** add unit tests for `_remove` and `_samelink`, update changelog.
Closes #47

SymlinkView: Fix symlink removal (fixes #47)

---

.travis.yml
tox.ini

Python 3.10 should have arrived on Travis, let's see whether it succeeds. I kept the default at 3.8, that's probably still more common than the very new 3.9.

Update tox and travis config for Python 3.10 alpha

---

beetsplug/alternatives.py

Small PR that adds support for respecting `convert`'s `threads` config. https://github.com/geigerzaehler/beets-alternatives/issues/41.
I didn't write any tests so that's now awesome but Works on My Machine™. 
The code located [here](https://github.com/geigerzaehler/beets-alternatives/blob/master/beetsplug/alternatives.py#L454) is probably also not needed or could be refactored to remove setting threads to CPU count since that should already be done via the `convert` plugin.

Respect convert's threads configuration

---

.github/workflows/main.yaml

The build against the preview version of Python may fail. In this case we allow the other builds to proceed.

Continue other builds if Python preview build fails

---

.github/workflows/main.yaml
DEVELOPING.md
beetsplug/alternatives.py
poetry.lock
pyproject.toml
test/cli_test.py
test/conftest.py
test/helper.py

We replace basic flake8 for linting and isort and black for formatting
with Ruff. We enable a couple of linters and fix the offending code.

Move to Ruff for linting and modernize code base

---

.github/workflows/main.yaml
CHANGELOG.md
poetry.lock
pyproject.toml

Allow beets v2 as dependency, use it in the lockfile and add a build against v1.6.1

Confirm support for beets v2

---

CHANGELOG.md
beetsplug/alternatives.py
pyproject.toml
test/helper.py

Internally, all paths are represented by `Path` instances instead of `bytes`. When we pass paths to beets code (`Item.write`, `beets.art.embed_item`) we explicitly convert it to `bytes`.
We replace the following beets utility functions with standard library versions that handle `Path`s.
- `beets.util.mkdirall` -> `Path.mkdir`
- `beets.util.link` -> `Path.symlink_to`
- `beets.util.copy` -> `shutil.copfyile`
- `beets.util.samefile` -> `Path.__eq__ `

Use pathlib instead of beets's path handling

---

README.md
beetsplug/alternatives.py
test/cli_test.py

This allows setting `album_art_maxwidth` (same setting name as in the convert plugin) to restrict the maximum size of the embedded album art.

Add maxwidth setting for album art

---

pyproject.toml
test/cli_test.py
test/helper.py

Follow-up to #108. Includes two more misc. test improvements

Skip tests failing on windows due to lacking environment

---

.github/workflows/main.yaml

This is not necessary since https://github.com/beetbox/beets/commit/916d40f86fadcd8bd52ee72c2db67f90a3e75619

Workaround pyright and mixed namepspaced packages
